### ISSUE TITLE
SFTP support via external binary

### ISSUE THREAD

**Issue by mordyovits** [janmojzis/tinyssh#1]
Given that tinyssh already supports channels in which stdin/stdout are from an external binary (e.g. bash), is there any reason not to add SFTP support?  It would require openssh's sftp-server binary, and a bit of code to accept the sftp channel type and run the sftp-server binary as the logged in user, but all of the support code for that is already in place.

**Comment by janmojzis** [comment]
No problem to implement it for example using '-x' switch:
tinysshd -x sftp=/usr/lib/openssh/sftp-server -x anothersubsystem=/somewhere/...
This will accept subsystem sftp and than run /usr/lib/openssh/sftp-server, and so on ...

**Comment by mordyovits** [comment]
That sounds like a great idea.

**Comment by mordyovits** [comment]
(But keep in mind that sftp-server does support cmdline args, e.g. -u for umask)

**Comment by janmojzis** [comment]
I think, it's no problem, command will looks like:
tinysshd -x 'sftp=/usr/lib/openssh/sftp-server -u 022 -d /somewhere'

**Comment by mordyovits** [comment]
Yeah, well openssh's sftp client screws up an equivalent cmdline arg: -D 
https://github.com/openssh/openssh-portable/blob/master/sftp.c#L2415
IOW, this happens:
`$ sftp -D '/usr/libexec/openssh/sftp-server -u 022'`
`exec: /usr/libexec/openssh/sftp-server -u 022: No such file or directory`
That's why I mentioned it.

**Comment by janmojzis** [comment]
Support for subsystem added, You can try it.
