### ISSUE TITLE
Build Error: tinysshd regression test failed

### ISSUE THREAD

**Issue by mettke** [janmojzis/tinyssh#13]
When I follow the Steps in https://tinyssh.org/install.html, I'll get the Error "tinysshd regression test failed" running make:
[make.log.txt](https://github.com/janmojzis/tinyssh/files/177997/make.log.txt)

Running "diff tinysshd.out tinysshd.exp" says:
```
480c480
< unable to send kex-message (broken pipe)
 ---
> unable to receive kex-message (connection reset)
```

**Comment by janmojzis** [comment]
Hello,
fixed here https://github.com/janmojzis/tinyssh/commit/9746b815d825b0e9eaa6e2f263eb46022933dc1b
