### ISSUE TITLE
buffer over-read in ed25519_parsesignpk

### ISSUE THREAD

**Issue by pascal-cuoq** [janmojzis/tinyssh#15]
The function `byte_isequal` is a constant-time comparison function that always reads all the bytes to compare.

In function `ed25519_parsesignpk`, the function `byte_isequal` is used to compare a string of an arbitrary length (chosen by the interlocutor) to the string literal `"ssh-ed25519"`:

https://github.com/janmojzis/tinyssh/blob/f5c4179f1a2724034c0fd1fc9aa6099768ade0a9/tinyssh/sshcrypto_key_ed25519.c#L51

It seems that a malicious interlocutor can send long strings to be passed to `ed25519_parsesignpk` in order to cause memory beyond `"ssh-ed25519"` to be read, with a crash as the consequence.

It is also possible that a malicious interlocutor might obtain all the contents of memory between the place where the string literal `"ssh-ed25519"` is stored and the first invalid page, one byte at a time, by sending successive strings that start with “ssh-ed25519”.

This issue was identified by @Karmaki and @miod.

**Comment by pascal-cuoq** [comment]
The function `ed25519_parsesignature` would have the same problem:

https://github.com/janmojzis/tinyssh/blob/f5c4179f1a2724034c0fd1fc9aa6099768ade0a9/tinyssh/sshcrypto_key_ed25519.c#L66

**Comment by janmojzis** [comment]
Hello,
thanks for report,
fixed here: https://github.com/janmojzis/tinyssh/commit/75d422a59f36dcdacdbfc07a83418b6d8f1907dd
