### ISSUE TITLE
Session timeout after 3600 seconds (1 hour)

### ISSUE THREAD

**Issue by plueschopath** [janmojzis/tinyssh#21]
I've noticed that my ssh sessions timeout after 3600 seconds. I think it's due to `alarm(3600)` that is set after the ssh session is created and also for some "refresh timeout" that I'm not really sure about what it really is.

The timeout seems to be there for "session rekeying" that should take place every hour. However I can't really find code in tinysshd.c that forces any kind of session rekying serverside, so the client needs to do that?

What's the use for those alarms? Is it really intended for session rekeying and if yes, how should one handle this in combination with OpenSSH on clientside?

OpenSSH_7.3p1 offers no session rekeying after N seconds as far as I can tell. Is it therefore safe to disable those alarms with a patch like this?

```
--- a/tinyssh/tinysshd.c
+++ b/tinyssh/tinysshd.c
@@ -170,7 +170,7 @@ rekeying:
     }
 
     /* note: user is authenticated and authorized */
-    alarm(3600);
+    alarm(0);
 
     /* main loop */
     for (;;) {
@@ -237,7 +237,7 @@ rekeying:
 
         /* receive data from network */
         if (watch0) {
-            alarm(3600); /* refresh timeout */
+            alarm(0); /* refresh timeout */
             if (!packet_recv()) {
                 if (channel_iseof()) break; /* XXX */
                 die_fatal("unable to receive data from network", 0, 0);

```

Thank you for your help.

**Comment by janmojzis** [comment]
Hello,
3600 second is 'idle' timeout. When the SSH session is idle (no SSH packets  received for more than 3600s) server will close the connection.
The timeout has 2 reasons:
- handling network timeouts
- automatic logout

When You don't need 'automatic logouts' You can refresh SSH session from client e.g. in OPENSSH using config option "ServerAliveInterval"

Jan

**Comment by plueschopath** [comment]
Hey Jan,

oh wow, and I thought `ServerAliveInterval` wasn't implemented cause I got `debug1: Received SSH2_MSG_UNIMPLEMENTED for N` on client side.

Works perfectly fine with it. Thank you and sorry for bothering you...
