### ISSUE TITLE
Developement status?

### ISSUE THREAD

**Issue by ArchangeGabriel** [janmojzis/tinyssh#25]
Hi there,

Development seems completely stalled. Is there anything happening?

Regards.

**Comment by janmojzis** [comment]
Hello, 
everything important is implemented.

In the fulture wil be also added some post-quantum algorithms, but it's long term run.

**Comment by 1Hyena** [comment]
@janmojzis 
are pull requests welcome? I would like to fork this project to implement authentication type `none` for forwarding anonymous SSH connections to a predefined (local)host:port over raw unencrypted TCP stream. This little addon would expose SSH to a wide variety of [new use cases](https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc).

**Comment by VA1DER** [comment]
> Hello,
> everything important is implemented.

Fixing sftp would be great.

**Comment by janmojzis** [comment]
> > Hello,
> > everything important is implemented.
> 
> Fixing sftp would be great.

problem reported here https://github.com/janmojzis/tinyssh/issues/54 is fixed,
and here https://github.com/janmojzis/tinyssh/issues/48 is also fixed
