### ISSUE TITLE
Secondary groups not working

### ISSUE THREAD

**Issue by midasi** [janmojzis/tinyssh#26]
We use tinyssh in combination with AlpineLinux. 

When log in with tinyssh the user has only the permissions from his primary group, but not from the secondary groups.

The secondary groups are also not shown with the commands 'id' or 'groups'

**Comment by janmojzis** [comment]
Hello, can You please check the version? Do You have latest version 20161101?

**Comment by midasi** [comment]
You're right, I used an old version.
With the newest version everything is working fine.
