### ISSUE TITLE
Banners are not implemented

### ISSUE THREAD

**Issue by midasi** [janmojzis/tinyssh#27]
The banners defined in /etc/issue and /etc/motd are currently not displayed.

It would be great if tinyssh could integrate this feature in the near future as these "disclaimers" are very important for your company.

**Comment by alexmyczko** [comment]
Does it respect `/etc/nologin`? (not from a quick search for it), see here for some special "standard" files:

https://github.com/xen0vas/UserManager/issues/8#issuecomment-622936119

**Comment by janmojzis** [comment]
hello,
banners from /etc/issue and /etc/motd are not displayed.

From my perspective it's not important feature. And can be implemented more easily e.g.:
/etc/profile line:
[ -f  /etc/motd ] && cat /etc/motd
