### ISSUE TITLE
Error While Building "emptytest.c"

### ISSUE THREAD

**Issue by adminy** [janmojzis/tinyssh#28]
channel_droptest.c:1:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before '.' token
 emptytest.c
          ^
=== Sun Aug 20 13:03:22 DST 2017 ===   channel_droptest failed ... see the log /mnt/c/Users/*****/Desktop/tinyssh-master/build/log

**Comment by janmojzis** [comment]
Sorry for late response,
is the problem still relevant?
