### ISSUE TITLE
Add option to disable root logins

### ISSUE THREAD

**Issue by itoffshore** [janmojzis/tinyssh#3]
I have `tinysshd` running without any problems in [Alpine Linux](http://alpinelinux.org) & will be introducing a `tinysshd` package to Alpine shortly. 

Can a switch be added to disable `root` logins please ?

**Comment by janmojzis** [comment]
>I have tinysshd running without any problems in Alpine Linux & will be introducing a tinysshd package to Alpine shortly.

Thank You!

>Can a switch be added to disable root logins please ?

Is it really necessary? You can simply remove e.g. /root/.ssh/authorized_keys and root login is disabled.

**Comment by itoffshore** [comment]
Yes of course you are right. There is also a solution to no scp - just use [Midnight Commander](https://midnight-commander.org/) - something like `mc ~/ sh://user@host:port` works with `tinysshd`.

I've [submitted a patch to include it as a package in Alpine](http://lists.alpinelinux.org/alpine-aports/0679.html) - but you may need to bring github up to date with the release & make a release on github.

**Comment by itoffshore** [comment]
I also managed to build `tinysshd` with [libsodium](https://github.com/jedisct1/libsodium) - it is a fork of NaCL / API compatible & currently maintained (it is used by [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) + others):
```
export LIBS="-lsodium"
export CFLAGS="$CFLAGS -I/usr/include/sodium"
export LDFLAGS="-L/usr/lib"
make
```
Please bring github up to date & make a release here.

**Comment by itoffshore** [comment]
`tinyssh` is now a [package in Alpine Linux](http://git.alpinelinux.org/cgit/aports/commit/?id=4b3500c9460597aacd032ea75391d5b44fd46fe1).

If you also put the releases on Github it is simple to keep track of them with the free [Sibbell service](https://sibbell.com/about/).
