### ISSUE TITLE
Agent forwarding

### ISSUE THREAD

**Issue by jailbird777** [janmojzis/tinyssh#30]
Are there any plans to add support for authentication agent forwarding?

I have a herd of SBCs (perfect for TinySSH) that I sometimes have to access via bastion.  Currently the only way to access them would be to put the private key on the bastion, which is less than ideal.

**Comment by 1Hyena** [comment]
@jailbird777 
have you looked at my pull request?

https://github.com/janmojzis/tinyssh/pull/29

could this be useful for you?

**Comment by jailbird777** [comment]
@1Hyena 

Your PR is useful for another project of mine (SSH enabling an old telnet FOSSIL BBS), but sadly doesn't replace the need for agent forwarding.

**Comment by janmojzis** [comment]
Hello,
"agent forwarding" is not implented in TinySSH.
And I'm not planing to add this feature.

manual page updated:
https://github.com/janmojzis/tinyssh/blob/master/man/tinysshd.8
