### ISSUE TITLE
Not building on OpenWrt

### ISSUE THREAD

**Issue by neheb** [janmojzis/tinyssh#38]
https://github.com/openwrt/packages/issues/7919

This is the build log: https://gist.github.com/neheb/0c11d413757bcb5957e39561e6803039

It seems the proper include directory is not there.

I have no real time to work on this, thus posting it here.

**Comment by janmojzis** [comment]
hello,
can You try make-tinysshcc.sh instead of make-tinyssh.sh.
make-tinyssh.sh runs test and the test failed:
"""
/bin/sh: 1: ./crypto_stream_chacha20test: Exec format error
"""

**Comment by neheb** [comment]
That did it. Almost. Now i get this error

```
sh -e make-install.sh /home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/tinyssh-20190101/ipkg-install
=== Mon Jan 28 20:55:10 UTC 2019 === /home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/tinyssh-20190101/build/bin/_tinysshd-install not compiled, compile first!
```

In the build directory, everything is there and compiled. I could just copy files from there manually. Would make more sense to try and fix this though.

**Comment by janmojzis** [comment]
fixed here: https://github.com/janmojzis/tinyssh/commit/1c1c99ba76a997783b64a9a7870f3d04de3a2e9f

**Comment by diizzyy** [comment]
Can confirm that it's working, thanks
