### ISSUE TITLE
Add conversion of private keys openssh

### ISSUE THREAD

**Issue by tetsumaki** [janmojzis/tinyssh#39]
Hello,

I think it could be very useful to add directly in this project the possibility of converting openssh keys to tinyssh format with a different binary file (tinyssh-convert) so you do not have a big binary (tinyssh).

I know that there is already an unofficial and functional project here : https://github.com/ansemjo/tinyssh-convert but no distribution includes it.

For information : domain dead at the bottom of page https://tinyssh.org/faq.html : https://git.semjonov.de/ansemjo/tinyssh-convert

**Comment by janmojzis** [comment]
hello,
thanks, the link at the bottom of page https://tinyssh.org/faq.html  changed to https://github.com/ansemjo/tinyssh-convert

**Comment by janmojzis** [comment]
conversion tool (written in python) included here: https://github.com/janmojzis/tinyssh/blob/master/tools/tinyssh-convert.py
