### ISSUE TITLE
sshfs, tinyssh

### ISSUE THREAD

**Issue by lulcat** [janmojzis/tinyssh#48]
current arhclinux, gives me this on a sshfs attempt.. not sure if bug or just a lacking feature?

 tinysshd: cVG3YoxN: BUG:  (protocol error){channel.c:214}
Not sure about the activity of project but you are a great dev mate!!

I HOPE what seems as a slowdown of activity is simply because of a fairly complete package ,)

love from EUrope to .cz.
Ok, so  that line indicates the channel pid is negative in channel_put.

Ignore error above; I didn't have sftp enabled in the tinysshd server. However, once I did, and can sftp in, I still get an error from tinyssh when trying sshfs:

tinysshd: eSIpVRao: BUG:  (connection reset){packet_auth.c:57}

l57:
 if (!packet_getall(b, SSH_MSG_USERAUTH_REQUEST)) bug();
SO some exchange issue, maybe I can browse some more tomorrow when I have more time. Although I don't recall if this is sshfs compatible (man sshfs saisi t used sftp which is why I realise the former mistake).

**Comment by lanodan** [comment]
Well if that helps it works fine here on gentoo with:
- OpenSSH 8.1_p1(-r3)
- tinyssh 20190101, arguments: ``-l -s -p -x sftp=/usr/lib64/misc/sftp-server /etc/tinyssh/keys``
- tcpserver from [ucspi-tcp](https://cr.yp.to/ucspi-tcp.html)
- sshfs 2.10(-r1)

Yeah, some parts in there are pretty old, it's running amd64 stable.

**Comment by VA1DER** [comment]
No change with latest release of tinyssh.

Is development active?

**Comment by lulcat** [comment]
Right lanodan, Thanks.. I haven't been on for a good while. I will have to return to it.. I think it was a lxc box or so, it's rare I go on an arch box so will have to revisit this some time. Thanks for your info though :)

**Comment by janmojzis** [comment]
Hello,
here is the fix https://github.com/janmojzis/tinyssh/tree/fixmaxpacket
which fixes the problem https://github.com/janmojzis/tinyssh/issues/54.
Can someone independently confirm,  if the fix also fixes the sshfs problem?

**Comment by lulcat** [comment]
@janmojzis I will be on my station later I think. Can check then if one else does. Cheers mate.

**Comment by lulcat** [comment]
Well. I was testing on my own distro and it works. I did get osme issues where possibly sshfs and not having a / at end didn't seem to find a folder. either that or it doesn't recognise hidden folders .. I don't know but it works. I don't have an arch lxc/vm right now. But I am sure I can get to test in the course of tomorrows. Great stuff! :) But ye, looks good.

**Comment by janmojzis** [comment]
The log message, fixed in this commit: https://github.com/janmojzis/tinyssh/commit/5a2f6c544b4c292755999b566459b8291a7862d5
