### ISSUE TITLE
On Windows

### ISSUE THREAD

**Issue by szepeviktor** [janmojzis/tinyssh#5]
Is it possible to compile tinyssh on Windows? For example on Cygwin?

**Comment by janmojzis** [comment]
Yes,
under cygwin compilation and tinyssh running works without problems.

**Comment by janmojzis** [comment]
updated FAQ: http://tinyssh.org/faq.html

**Comment by szepeviktor** [comment]
Thank you.
I plan to report compile success.

**Comment by szepeviktor** [comment]
- `conf-bin` contained `/usr/sbin`, I had to modify it to `sbin` and run `make-install.sh /usr`
- and commented out `chown 0:0`, there's no root on Cygwin

**Comment by janmojzis** [comment]
make-install.sh should also work.
Here is the fix:￼
https://github.com/janmojzis/tinyssh/commit/1c555dbe630c2b9e4fdb5d3fb989e51878a51f0a

**Comment by szepeviktor** [comment]
Thank you!
