### ISSUE TITLE
sntrup761

### ISSUE THREAD

**Issue by orachas** [janmojzis/tinyssh#50]
It appears that sntrup4591761x25519-sha512@tinyssh.org was removed from OpenSSH, and replaced with sntrup761x25519-sha512@openssh.com, at the behest of Daniel J. Bernstein.

> "Per the authors, sntrup4591761 was replaced almost two years ago by sntrup761."

Can this key exchange be implemented in tinyssh?

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/kexsntrup761x25519.c

**Comment by janmojzis** [comment]
work in progress here: https://github.com/janmojzis/tinyssh/tree/sntrup761x25519-sha512%40openssh.com

**Comment by janmojzis** [comment]
merged
