### ISSUE TITLE
improve documentation ; provide howto

### ISSUE THREAD

**Issue by setop** [janmojzis/tinyssh#53]
I discovered Tinyssh in alpine using `apk search ssh`. I wanted to install a ssh server in a container.

I really value small software when dealing with security (less code, less bug, less vulnerabilities).

But I did not manage to use it due to lack of documentation.

There seem to be [options](https://github.com/janmojzis/tinyssh/blob/41ca067ab1ab87888a38e6edc702d4cdda943ec8/tinyssh/main_tinysshd.c#L81), but not documented.

When I launch the exe, it ends up with a timeout whereas I was expecting a daemon.

The home page says 'which implements only a subset of SSHv2 features' but they are not listed. Basically I was wondering if it supports port forwarding.

I'm sure this tool deserve a proper readme.

In the meantime, I'll try to setup opensshd without exposing my system too much.

**Comment by janmojzis** [comment]
readme update: #56

**Comment by setop** [comment]
Thanks
