### ISSUE TITLE
aarch64 build

### ISSUE THREAD

**Issue by MisteryX** [janmojzis/tinyssh#57]
Hi guys. I'm trying to build tinyssh from source (`apt source tinysshd`) in Ubuntu 20.04.2 (amd64) using crosscompiler
`CC=aarch64-linux-gnu-gcc make` for ARMv8

before make I did `sudo apt-get build-dep tinyssh`, but It did not help much.

Build fails on libtinynacl.a failed ... see the log /home/user/tinyssh-20190101/build/log
First it wanted libutil.h, so I installed `sudo apt install libutil-freebsd-dev`
But it wants a lot of other includes...  

Are there any build images? How could I find nessesary libs and headers for build?

In file included from haslibutilh.h-yes.c:2:
/usr/include/libutil.h:43:10: fatal error: sys/_types.h: No such file or directory
   43 | #include <sys/_types.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
hasutilh.h-yes.c:2:10: fatal error: util.h: No such file or directory
    2 | #include <util.h>
      |          ^~~~~~~~
compilation terminated.
hasutmpxupdwtmpx.h-yes.c: In function 'foo':
hasutmpxupdwtmpx.h-yes.c:6:5: warning: implicit declaration of function 'updwtmpx' [-Wimplicit-function-declaration]
    6 |     updwtmpx("/nonexistent", &ut);
      |     ^~~~~~~~
hasutmpxsyslen.h-yes.c: In function 'main':
hasutmpxsyslen.h-yes.c:7:14: error: 'struct utmpx' has no member named 'ut_syslen'
    7 |     return ut.ut_syslen;
      |              ^
hasutmpxsyslen.h-yes.c:6:18: warning: variable 'ut' set but not used [-Wunused-but-set-variable]
    6 |     struct utmpx ut = {0};
      |                  ^~
hasutmp.h-yes.c: In function 'main':
hasutmp.h-yes.c:8:17: warning: unused variable 'ut' [-Wunused-variable]
    8 |     struct utmp ut = {0};
      |                 ^~
hasutmptype.h-yes.c: In function 'main':
hasutmptype.h-yes.c:8:17: warning: variable 'ut' set but not used [-Wunused-but-set-variable]
    8 |     struct utmp ut;
      |                 ^~
=== Wed May 26 16:08:35 2021 === finishing
=== Wed May 26 16:08:35 2021 === starting crypto lib
cleanup.c:2:10: fatal error: hasasmvolatilememory.h: No such file or directory
    2 | #include "hasasmvolatilememory.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
=== Wed May 26 16:08:36 2021 ===   libtinynacl.a failed ... see the log /home/user/tinyssh-20190101/build/log

**Comment by alexmyczko** [comment]
i'm able to build it with debian 11 on arm64 raspberry pi 3 or 4 hardware.

**Comment by janmojzis** [comment]
debian 11 e.g:
~~~
apt-get install gcc-10-aarch64-linux-gnu
CC=/usr/bin/aarch64-linux-gnu-gcc-10 ./make-tinysshcc.sh
~~~

**Comment by janmojzis** [comment]
Is it still a problem ?

**Comment by windoozatnick** [comment]
I'm getting a similar error.

I am compiling from ubuntu arm64 for the armv7l platform, and using the gcc-arm-linux-gnueabihf compiler

I passed the parameter `export CC=arm-linux-gnueabihf-gcc`, and specified in the **conf-cc** and **conf-ar** files the paths to `/usr/bin/arm-linux-gnueabihf-gcc` and `/usr/bin/arm-linux-gnueabihf-ar`, respectively. 

And I still get this error - what am I doing wrong?

```
cleanup.c:2:10: fatal error: hasasmvolatilememory.h: No such file or directory
    2 | #include "hasasmvolatilememory.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
