### ISSUE TITLE
update to the new name crypto

### ISSUE THREAD

**Issue by TNTBOMBOM** [janmojzis/tinyssh#58]
Hi There, 

Looking here: 

https://github.com/janmojzis/tinyssh#crypto-primitives

it uses "curve25519-sha256@libssh.org" this is i believe the old name and new name removed @libssh.org: 

https://github.com/openssh/openssh-portable/blob/6116bd4ed354a71a733c8fd0f0467ce612f12911/kex.h#L63

ThX!

**Comment by janmojzis** [comment]
Thanks,
README fixed.
TinySSH support both:
- (new) https://github.com/janmojzis/tinyssh/blob/master/tinyssh/sshcrypto_kex.c#L18
- (old) https://github.com/janmojzis/tinyssh/blob/master/tinyssh/sshcrypto_kex.c#L29
