### ISSUE TITLE
Client?

### ISSUE THREAD

**Issue by snvmk** [janmojzis/tinyssh#61]
Hi, i installed this server on my raspberry pi, but, which client should i use? (i use git, so i need to have ssh client to do pushes)

**Comment by janmojzis** [comment]
Hello,
tinyssh is server only.

You can use e.g. openssh-client.

~~~
apt-get install openssh-client
~~~

**Comment by snvmk** [comment]
Oh, okay, i ll look at it. Btw in alpine there is openssh-client-default and -common. Do you know the difference?

**Comment by snvmk** [comment]
And other question, so, i cant use tinyssh key when i'm doing `git clone git@github.com:cool/repo`?

**Comment by janmojzis** [comment]
not related to tinyssh server
