### ISSUE TITLE
SCP does not work in latest version

### ISSUE THREAD

**Issue by petrkutalek** [janmojzis/tinyssh#63]
After upgrade to latest version 20220222-1 (Arch) SCP does not work anymore, SSH works all right.

Client: `client_loop: send disconnect: Broken pipe`, `lost connection`
Server's log: `tinysshd[929]: tinysshd: JLiyKgwc: BUG:  (protocol error){sshcrypto_cipher_chachapoly.c:88}`

**Comment by janmojzis** [comment]
Hello,
The problem is related to the openssh upgrade from 8.8 -> 8.9.
fixed (added workaround) in today's version 20220305 (latest commit)

**Comment by petrkutalek** [comment]
Thanks a lot! Appreciated. I notified Arch maintainers to update [tinyssh package](https://archlinux.org/packages/community/x86_64/tinyssh/) in Arch distro.

**Comment by petrkutalek** [comment]
[tinyssh package](https://archlinux.org/packages/community/x86_64/tinyssh/) was updated in Arch; I have checked it, everything works all right now. Thanks a lot!
