### ISSUE TITLE
"No" for Putty?

### ISSUE THREAD

**Issue by szepeviktor** [janmojzis/tinyssh#7]
I think putty 0.65 and tinyssh has no common algorithm.
http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

**Comment by szepeviktor** [comment]
After generating an ed25519 key with [unreleased puttygen](http://tartarus.org/~simon/putty-snapshots/x86/)
```
tinysshd: Vc2t8YZ4: debug: hello: server: SSH-2.0-tinyssh_20150801 Vc2t8YZ4 {packet_hello.c:38}
tinysshd: Vc2t8YZ4: debug: hello: client: SSH-2.0-PuTTY_Snapshot_2015_09_11.43be90e (temporary failure){packet_hello.c:61}
tinysshd: Vc2t8YZ4: debug: kex: server: kex algorithms: curve25519-sha256@libssh.org (temporary failure){sshcrypto_kex.c:137}
tinysshd: Vc2t8YZ4: debug: kex: server: key algorithms: ssh-ed25519 (temporary failure){sshcrypto_key.c:156}
tinysshd: Vc2t8YZ4: debug: kex: server: cipher algorithms: chacha20-poly1305@openssh.com (temporary failure){sshcrypto_cipher.c:142}
tinysshd: Vc2t8YZ4: debug: kex: server: cipher algorithms: chacha20-poly1305@openssh.com (temporary failure){sshcrypto_cipher.c:142}
tinysshd: Vc2t8YZ4: debug: kex: server: mac algorithms: chacha20-poly1305@openssh.com (temporary failure){sshcrypto_cipher.c:165}
tinysshd: Vc2t8YZ4: debug: kex: server: mac algorithms: chacha20-poly1305@openssh.com (temporary failure){sshcrypto_cipher.c:165}
tinysshd: Vc2t8YZ4: debug: kex: client: kex algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,rsa2048-sha256,rsa1024-sha1 (temporary failure){sshcrypto_kex.c:85}
tinysshd: Vc2t8YZ4: info: kex: kex selected: curve25519-sha256@libssh.org {sshcrypto_kex.c:106}
tinysshd: Vc2t8YZ4: debug: kex: client: key algorithms: ssh-rsa,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-dss (temporary failure){sshcrypto_key.c:104}
tinysshd: Vc2t8YZ4: info: kex: key selected: ssh-ed25519 {sshcrypto_key.c:122}
tinysshd: Vc2t8YZ4: debug: kex: client: cipher algorithms: aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128,chacha20-poly1305@openssh.com (temporary failure){sshcrypto_cipher.c:91}
tinysshd: Vc2t8YZ4: info: kex: cipher selected: chacha20-poly1305@openssh.com {sshcrypto_cipher.c:110}
tinysshd: Vc2t8YZ4: info: kex: mac selected: chacha20-poly1305@openssh.com {sshcrypto_cipher.c:111}
```

**Comment by szepeviktor** [comment]
I would strangely use tinyssh to reach cmd.exe in Putty. Because you need some kind of server accomplish that.

**Comment by janmojzis** [comment]
hmmm,
there is very probably problem in chacha20-poly1305@openssh.com implementation in putty.
https://github.com/jhcloos/openssh-chacha-poly1305/blob/master/PROTOCOL.chacha20poly1305
section negotiation:
The chacha20-poly1305@openssh.com offers both encryption and
authentication. As such, no separate MAC is required. If the
chacha20-poly1305@openssh.com cipher is selected in key exchange,
the offered MAC algorithms are ignored and no MAC is required to be
negotiated.

can You pls try this patch (only logs MAC request): https://github.com/janmojzis/tinyssh/commit/995656bd3f66fa2ab5a57f39aa373de267d9d4c6

**Comment by janmojzis** [comment]
workaround for testing, you can run tinyssh with switch '-o' (older encryption primitives)
and Your putty will use aes128-ctr + hmac-sha2-256

**Comment by janmojzis** [comment]
definitely bug in PUTTY,
workarounded here:
https://github.com/janmojzis/tinyssh/commit/9280210ff308c1768ceb136347eac617a96639ff

now it should work without '-o' parameter

**Comment by szepeviktor** [comment]
Thank you. I try to report that bug.

**Comment by szepeviktor** [comment]
My bug report is kind a lame but sent.

**Comment by janmojzis** [comment]
Can You also try latest tinyssh version? Should work using current Putty.

**Comment by szepeviktor** [comment]
Fixed :smile: 
http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=commit;h=5f6e443b55d9d2c53b0aadc857181ec377c95e18
