### ISSUE TITLE
Nice mixture of wrong, inconsistent and non-relevant information

### ISSUE THREAD

**Issue by Ricky-Tigg** [janmojzis/tinyssh#73]
Hello! I hope i didn't wake anyone. No? Good.

Source: https://tinyssh.org/

_Wrong_ | "_Postquantum crypto: (...) chacha20-poly1305_"; It is certainly nott part of the PQ algorithm family but an **AEAD**. It is out of scope of PQ research. See relevant sources. Post-quantum cryptographic primitive sntrup761x25519-sha512@openssh.com and AEAD chacha20-poly1305@openssh.com were introduced in [OpenSSH](https://www.openssh.com/releasenotes.html) respectively in v. 8.5, now as default in v. 9.0, and v. 6.5, promoted as default cipher in v. 6.9. Worht noting: OpenSSL and OpenSSH differ each other in regard to software policies. OpenSSL, unlike OpenSSH, solely incorporates to its project algorithm implementations which have been standardised by a recognised national or internal standards entity. At this time there is no such standard for NTRU. NIST recently [decided](https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8413.pdf#page=47&zoom=100,120,546) not to standardise NTRU. That's instead CRYSTALS-Kyber that was selected for standardisation. I guess that allows this project developer to state _So TinySSH is in good company here!_

Source: https://tinyssh.org/faq.html

_inconsistent_ | "_TinySSH has less than100000 words of code_". It appears to be less than 50000. Take a look at the dust on that page; indeed, no surprise; that's year _2014_ in command output! that one i liked. So since you like playing with numbers, let's state here _200000_. That gives the project time to let an even thicker layer of dust growing. That's an achievement like another.

_non-relevant_ | "_TinySSH is promising ‘no older cryptographic primitives’, but md5 is available in crypto library. What does it mean? (...) since version 20150201 tinysshd-printkey is not using MD5, MD5 removed._". You are a fast-learner aren't you? So take a look at the dust here; that's year _2015_. What is your point here? An exhibition of _good-old-time memories_ to amuse us, readers?.

That much for today. All but serious matter.

**Comment by felixfontein** [comment]
> _Wrong_ | "_Postquantum crypto: (...) chacha20-poly1305_"; It is certainly nott part of the PQ algorithm family but an **AEAD**.

This is something you are wrong about: basically all symmetric ciphers are also post-quantum symmetric ciphers, since there are no quantum attacks against them more efficient than basic Grover search. So assuming the key length isn't too small, and there aren't specific Quantum attacks against them, basically all symmetric ciphers are also PQ ciphers.

**Comment by Ricky-Tigg** [comment]
But no, everything is fine. Was it so worth warming up to? For those who know how to pay attention to what is left ignored and unwritten and to what given for reading, that is not that _SSH_ that is that _tiny_ as we just learned, but unmistakably something else. As you may not suspect, it's not yet today that I'm going to entrust you with a task of development work. You will understand I wouldn't want to cover myself with ridicule for trifles. Why don't you leave everything as it is and leave the building._ Isn't that an idea? You shall see for yourself that it will do you the greatest good.  I almost forgot to tell you –_basically_.

**Comment by Ricky-Tigg** [comment]
But no, everything is fine. Was it so worth warming up to? For those who know how to pay attention to what is left ignored and unwritten and to what is given for reading, that is not that _SSH_ that is that _tiny_ as we just learned, but unmistakably something else. As you may not suspect, it's not yet today that I'm going to entrust you with a task of development work. You will understand I wouldn't want to cover myself with ridicule for trifles. Why don't you leave everything as it is and leave the building._ Isn't that an idea? You shall see for yourself that it will do you the greatest good.  I almost forgot to tell you –_basically_.

**Comment by Ricky-Tigg** [comment]
But no, everything is fine. Was it so worth warming up to? For those who know how to pay attention to what is left ignored and unwritten and to what is given for reading, that is not that _SSH_ that is that _tiny_ as we just learned, but unmistakably something else. As you may not suspect, it's not yet today that I'm going to entrust you with a task of development work. You will understand I wouldn't want to cover myself with ridicule for trifles. Why don't you leave everything as it is and leave the building. Isn't that an idea? You shall see for yourself that it will do you the greatest good. I almost forgot to tell you – _basically_.
