### ISSUE TITLE
Where to get GPG key to verify your signatures?

### ISSUE THREAD

**Issue by vt-alt** [janmojzis/tinyssh#75]
Where to find your GPG keys to verify tar and git tag signatures?
I cannot find them on tinyssh web page. But you [mention to use them:](https://tinyssh.org/install.html)
```
$ gpg2 --verify 20230101.tar.gz.asc 20230101.tar.gz
gpg: Signature made Sun 01 Jan 2023 02:35:41 AM MSK
gpg:                using RSA key D008B0C23D8479E46B9FCB9045DA517496939FF9
gpg: Can't check signature: No public key
```
Key search D008B0C23D8479E46B9FCB9045DA517496939FF9 from keys.openpgp.org gives https://keys.openpgp.org/vks/v1/by-fingerprint/AADF2EDF5529F1702772C8A2DEC4D246931EF49B which is not usable:
```
$ gpg2 --import AADF2EDF5529F1702772C8A2DEC4D246931EF49B
gpg: key DEC4D246931EF49B: no user ID
gpg: Total number processed: 1
```
Also, there's no key at https://github.com/janmojzis.gpg
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded DEC4D246931EF49B


=twTO
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by janmojzis** [comment]
https://github.com/janmojzis.gpg should work now.
Key reuploaded.

**Comment by vt-alt** [comment]
Thanks!
